### ISSUE TITLE
Single quotes ruin everything

### ISSUE THREAD

**Issue by bobdesaunois** [CompraBV/CompraSiteMapper#1]
Currently once single quotes are encountered the system grinds to a full halt.
So instead of `href="http://google.com/"` we'd get `href='http://google.com/'`

Currently the way the system handles this is quite depressing.

**Comment by bobdesaunois** [comment]
"once single quotes are encountered the system grinds to a full halt."
is a flat out lie.
They don't halt, they actually infinitely loop, which sucks, balls.
Balls without errors, that is.

**Comment by StefanoGroenland** [comment]
!

**Comment by bobdesaunois** [comment]
Fixed breh
