### ISSUE TITLE
Crawler doesn't go in depth

### ISSUE THREAD

**Issue by bobdesaunois** [CompraBV/CompraSiteMapper#3]
Several loops should commence where the system reiteratively goes over all the newly acquired URLs
so it may extend itself beyond the first and second depth.
However this process should be halted once it reaches a certain configurable depth (`MAX_DEPTH` @ `nl.compra.CompraCrawler.Brain`).

**Comment by bobdesaunois** [comment]
![deeper](https://cloud.githubusercontent.com/assets/6050628/12238249/603f2e3c-b883-11e5-8502-985b25566ada.jpg)

**Comment by bobdesaunois** [comment]
Does.

**Comment by NathanBastiaans** [comment]
well maymay-ed

**Comment by bobdesaunois** [comment]
![](http://static2.fjcdn.com/comments/I+believe+he+may+have+a+posterior+paroxysm+_54a4f2d548c5a9018804ed53017a6f9f.jpg)
